### ISSUE TITLE
renderFile and renderFileAsync

### ISSUE THREAD

**Issue by RobLoach** [jstransformers/jstransformer-toml#1]
Those seem like they could be moved into https://github.com/jstransformers/jstransformer . Look like they're the same as the other transformers you've put together.

**Comment by TimothyGu** [comment]
Thing is, they already do not need to be like this. jstranformer already provides an easy abstraction for all the Promise vs callback stuff, so only `render` should be needed.

**Comment by TimothyGu** [comment]
Apparently nobody here knows how jstransformer works, and therefore I think some documentation enhancement should be in place jstransformers/jstransformer#10.

**Comment by RobLoach** [comment]
So remove those functions!

**Comment by tunnckoCore** [comment]
> Thing is, they already do not need to be like this

really? hm, I'll check.

**Comment by tunnckoCore** [comment]
@TimothyGu it seems we need them.

When I leave only `render` function it throws

```
TypeError: undefined is not a function
```

**Comment by ForbesLindesay** [comment]
You have to do `require('jstransformer')(require('jstransformer-toml'))` rather than `require('jstransformer-toml')`

**Comment by tunnckoCore** [comment]
oooh, yea. so we should use jstransformer in testing :) cool.

**Comment by tunnckoCore** [comment]
hm, cool. I'll update the libs.
@ForbesLindesay but one question, why not use `bluebird` instead of `promise` when users would search performance in async? Cuz I think one usage case of `jstransformer` is building tools/apis/engines on top of it.

**Comment by tunnckoCore** [comment]
done

**Comment by ForbesLindesay** [comment]
You don't need jstransformer in testing.  You just need to only test the method you're implrmenting.

We use promise instead of bluebird for two reasons:
1. Bluebird is not a standards compliant implementation of ES6 promises and instead it has loads of pointless extensions that nobody wants.  I don't want to encourage people to use those extensions.
2. I maintain Promise
